services:
- type: web
  name: azm-chashbox
  runtime: docker
  envVars:
  - key: SECRET_KEY
    generateValue: true
  - key: SESSION_COOKIE_SECURE
    value: "1"
  - key: DATABASE_URL
    sync: false
